In [238]:
import pandas as pd
import numpy as np

In [239]:
df=pd.read_csv("Sales.csv")

In [240]:
pd.DataFrame(df)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,01-01-2016,NaN,265598,10,1304,1,CAD
1,366001,1,01-01-2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,01-01-2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,01-01-2016,01-12-2016,266019,0,1106,7,CAD
4,366002,2,01-01-2016,01-12-2016,266019,0,373,1,CAD
...,...,...,...,...,...,...,...,...,...
62879,2243030,1,2/20/2021,NaN,1216913,43,632,3,USD
62880,2243031,1,2/20/2021,2/24/2021,511229,0,98,4,EUR
62881,2243032,1,2/20/2021,2/23/2021,331277,0,1613,2,CAD
62882,2243032,2,2/20/2021,2/23/2021,331277,0,1717,2,CAD
62883,2243032,3,2/20/2021,2/23/2021,331277,0,464,7,CAD

In [241]:
df.shape

(62884, 9)

In [242]:
df.columns

Index(['Order Number', 'Line Item', 'Order Date', 'Delivery Date',
       'CustomerKey', 'StoreKey', 'ProductKey', 'Quantity', 'Currency Code'],
      dtype='object')

In [243]:
df.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,01-01-2016,NaN,265598,10,1304,1,CAD
1,366001,1,01-01-2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,01-01-2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,01-01-2016,01-12-2016,266019,0,1106,7,CAD
4,366002,2,01-01-2016,01-12-2016,266019,0,373,1,CAD

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Number   62884 non-null  int64
 1   Line Item      62884 non-null  int64
 2   Order Date     62884 non-null  object
 3   Delivery Date  13165 non-null  object
 4   CustomerKey    62884 non-null  int64
 5   StoreKey       62884 non-null  int64
 6   ProductKey     62884 non-null  int64
 7   Quantity       62884 non-null  int64
 8   Currency Code  62884 non-null  object
dtypes: int64(6), object(3)
memory usage: 4.3+ MB

In [245]:
df["Delivery Date"].isna().sum()

np.int64(49719)

In [246]:
df[df["Delivery Date"].isna()].head(10)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,01-01-2016,NaN,265598,10,1304,1,CAD
6,366004,1,01-01-2016,NaN,1107461,38,163,6,GBP
7,366004,2,01-01-2016,NaN,1107461,38,1529,2,GBP
8,366005,1,01-01-2016,NaN,844003,33,421,4,EUR
9,366007,1,01-01-2016,NaN,2035771,43,1617,1,USD
10,366007,2,01-01-2016,NaN,2035771,43,666,5,USD
11,366008,1,01-01-2016,NaN,759705,29,1154,9,EUR
12,366008,2,01-01-2016,NaN,759705,29,2510,1,EUR
13,366008,3,01-01-2016,NaN,759705,29,1060,5,EUR
14,366009,1,01-01-2016,NaN,254540,9,1648,1,CAD

In [247]:
df[df["Delivery Date"].isna()]["Order Date"].value_counts().head(10)

Order Date
01-04-2020    173
12/29/2018    172
12/28/2019    172
12/21/2019    169
12/27/2018    157
2/22/2020     156
01-01-2020    150
2/15/2020     149
12/26/2019    147
01-05-2019    145
Name: count, dtype: int64

In [248]:
missing_delivery = df["Delivery Date"].isna().sum()
total_rows = len(df)

missing_delivery / total_rows * 100

np.float64(79.064626932129)

In [249]:
df["Delivery Date"].notna().sum() / len(df) * 100

np.float64(20.935373067870998)

In [250]:
df.isna().sum()

Order Number         0
Line Item            0
Order Date           0
Delivery Date    49719
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency Code        0
dtype: int64

In [251]:
df.duplicated().sum()

np.int64(0)

In [252]:
# Composite Key
df.duplicated(subset=["Order Number", "Line Item"]).sum()

np.int64(0)

In [253]:
df["Order Number"].unique()

array([ 366000,  366001,  366002, ..., 2243030, 2243031, 2243032],
      shape=(26326,))

In [254]:
len(df)

62884

In [255]:
#Quantity (Check for any 0 or negative values present)
df["Quantity"].max()

np.int64(10)

In [256]:
df["Quantity"].min()

np.int64(1)

In [257]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Order Number, Line Item, Order Date, Delivery Date, CustomerKey, StoreKey, ProductKey, Quantity, Currency Code]
Index: []

In [258]:
#Checking for formats for order Date and delivery date
df["Order Date"].head(20).tolist()

['01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016',
 '01-01-2016']

In [259]:
df["Delivery Date"].head(20).tolist()

[nan,
 '1/13/2016',
 '1/13/2016',
 '01-12-2016',
 '01-12-2016',
 '01-12-2016',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '01-08-2016',
 nan,
 nan,
 nan,
 nan]

In [260]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="mixed",
    errors="coerce"
)

df["Delivery Date"] = pd.to_datetime(
    df["Delivery Date"],
    format="mixed",
    errors="coerce"
)

In [261]:
df[["Order Date", "Delivery Date"]].head(10)

  Order Date Delivery Date
0 2016-01-01           NaT
1 2016-01-01    2016-01-13
2 2016-01-01    2016-01-13
3 2016-01-01    2016-01-12
4 2016-01-01    2016-01-12
5 2016-01-01    2016-01-12
6 2016-01-01           NaT
7 2016-01-01           NaT
8 2016-01-01           NaT
9 2016-01-01           NaT

In [262]:
df[["Order Date", "Delivery Date"]].dtypes

Order Date       datetime64[ns]
Delivery Date    datetime64[ns]
dtype: object

In [263]:
#Check for invalid Delivery date
df[df["Order Date"] < df["Delivery Date"]]

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
1,366001,1,2016-01-01,2016-01-13,1269051,0,1048,2,USD
2,366001,2,2016-01-01,2016-01-13,1269051,0,2007,1,USD
3,366002,1,2016-01-01,2016-01-12,266019,0,1106,7,CAD
4,366002,2,2016-01-01,2016-01-12,266019,0,373,1,CAD
5,366002,3,2016-01-01,2016-01-12,266019,0,1080,4,CAD
...,...,...,...,...,...,...,...,...,...
62878,2243029,6,2021-02-20,2021-02-27,887764,0,1456,2,EUR
62880,2243031,1,2021-02-20,2021-02-24,511229,0,98,4,EUR
62881,2243032,1,2021-02-20,2021-02-23,331277,0,1613,2,CAD
62882,2243032,2,2021-02-20,2021-02-23,331277,0,1717,2,CAD
62883,2243032,3,2021-02-20,2021-02-23,331277,0,464,7,CAD

In [264]:
(df["Delivery Date"] < df["Order Date"]).sum()

np.int64(0)

In [265]:
#check for unsual date
df["Order Date"].min()

Timestamp('2016-01-01 00:00:00')

In [266]:
df["Order Date"].max()

Timestamp('2021-02-20 00:00:00')

In [267]:
df["Delivery Date"].min()

Timestamp('2016-01-06 00:00:00')

In [268]:
df["Delivery Date"].max()

Timestamp('2021-02-27 00:00:00')

In [269]:
#Currency code
df["Currency Code"].unique()

array(['CAD', 'USD', 'GBP', 'EUR', 'AUD'], dtype=object)

In [270]:
df["Currency Code"].value_counts()

Currency Code
USD    33767
EUR    12621
GBP     8140
CAD     5415
AUD     2941
Name: count, dtype: int64

In [271]:
#Line Item
df["Line Item"].unique()

array([1, 2, 3, 4, 5, 6, 7])

In [272]:
#StoreKey
df["StoreKey"].nunique()

58

In [273]:
#ProductKey
df["ProductKey"].nunique()

2492

In [274]:
#Investigate the missing Delivery Date
df[df["Delivery Date"].isna()]["Order Date"].min()

Timestamp('2016-01-01 00:00:00')

In [275]:
df[df["Delivery Date"].isna()]["Order Date"].max()

Timestamp('2021-02-20 00:00:00')

In [276]:
df[df["Delivery Date"].isna()]["Order Date"].dt.year.value_counts().sort_index()

Order Date
2016     5744
2017     6396
2018    11244
2019    16917
2020     8539
2021      879
Name: count, dtype: int64

In [277]:
missing_delivery_by_year = (
    df.groupby(df["Order Date"].dt.year)["Delivery Date"]
    .apply(lambda x: x.isna().sum()/ len(x) * 100)
)

missing_delivery_by_year

Order Date
2016    83.186097
2017    80.533871
2018    79.250070
2019    78.279580
2020    77.444223
2021    72.524752
Name: Delivery Date, dtype: float64

In [278]:
missing_delivery_by_year = df.groupby(
    df["Order Date"].dt.year
)["Delivery Date"].apply(
    lambda x: x.isna().mean() * 100
)

print(missing_delivery_by_year)

Order Date
2016    83.186097
2017    80.533871
2018    79.250070
2019    78.279580
2020    77.444223
2021    72.524752
Name: Delivery Date, dtype: float64

In [279]:
#checking for missing values in categorical/key columns
df[["Order Number", "Line Item", "CustomerKey", "StoreKey", "ProductKey", "Quantity", "Currency Code"]].isna().sum()

Order Number     0
Line Item        0
CustomerKey      0
StoreKey         0
ProductKey       0
Quantity         0
Currency Code    0
dtype: int64

In [280]:
df.dtypes

Order Number              int64
Line Item                 int64
Order Date       datetime64[ns]
Delivery Date    datetime64[ns]
CustomerKey               int64
StoreKey                  int64
ProductKey                int64
Quantity                  int64
Currency Code            object
dtype: object

# Customer Table

In [281]:
#Load Customers Table
customers = pd.read_csv("Customers.csv", encoding="latin1")

In [282]:
customers.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,07-03-1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [283]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15266 entries, 0 to 15265
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerKey  15266 non-null  int64
 1   Gender       15266 non-null  object
 2   Name         15266 non-null  object
 3   City         15266 non-null  object
 4   State Code   15256 non-null  object
 5   State        15266 non-null  object
 6   Zip Code     15266 non-null  object
 7   Country      15266 non-null  object
 8   Continent    15266 non-null  object
 9   Birthday     15266 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.2+ MB

In [284]:
customers["Birthday"].head(20).tolist()

['07-03-1939',
 '9/27/1979',
 '5/26/1947',
 '9/17/1957',
 '11/19/1965',
 '1/20/1954',
 '11/22/1969',
 '03-12-1950',
 '12/21/1965',
 '7/25/1975',
 '08-12-1990',
 '10/17/1985',
 '03-03-1965',
 '11/22/1964',
 '07-10-1986',
 '9/22/1984',
 '9/20/1974',
 '10/31/1969',
 '12/15/1987',
 '04-01-1968']

In [285]:
customers["Birthday"].isna().sum()

np.int64(0)

In [286]:
customers["Birthday"].nunique()

11270

In [287]:
customers["Birthday"] = pd.to_datetime(
    customers["Birthday"],
    format="mixed",
    errors="coerce"
)

In [288]:
customers["Birthday"].dtype

dtype('<M8[ns]')

In [289]:
customers["Birthday"].isna().sum()

np.int64(0)

In [290]:
customers["CustomerKey"].duplicated().sum()

np.int64(0)

In [291]:
customers["CustomerKey"].nunique()

15266

In [292]:
df["CustomerKey"].isin(customers["CustomerKey"]).sum()

np.int64(62884)

In [293]:
#This shows how many customerKey of sales table are actaully exist in customers table
df["CustomerKey"].isin(customers["CustomerKey"]).mean() * 100

np.float64(100.0)

In [294]:
df[~df["CustomerKey"].isin(customers["CustomerKey"])]

Empty DataFrame
Columns: [Order Number, Line Item, Order Date, Delivery Date, CustomerKey, StoreKey, ProductKey, Quantity, Currency Code]
Index: []

# Store Table

In [295]:
stores = pd.read_csv("Stores.csv")

In [296]:
stores.shape

(67, 5)

In [297]:
stores.columns

Index(['StoreKey', 'Country', 'State', 'Square Meters', 'Open Date'], dtype='object')

In [298]:
stores.head()

,StoreKey,Country,State,Square Meters,Open Date
0,1,Australia,Australian Capital Territory,595.0,01-01-2008
1,2,Australia,Northern Territory,665.0,01-12-2008
2,3,Australia,South Australia,2000.0,01-07-2012
3,4,Australia,Tasmania,2000.0,01-01-2010
4,5,Australia,Victoria,2000.0,12-09-2015

In [299]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StoreKey       67 non-null     int64
 1   Country        67 non-null     object
 2   State          67 non-null     object
 3   Square Meters  66 non-null     float64
 4   Open Date      67 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.7+ KB

In [300]:
stores["Open Date"].head(20).tolist()

['01-01-2008',
 '01-12-2008',
 '01-07-2012',
 '01-01-2010',
 '12-09-2015',
 '01-01-2010',
 '05-07-2007',
 '07-02-2014',
 '03-04-2005',
 '04-04-2015',
 '06-03-2009',
 '06-06-2012',
 '06-07-2013',
 '12/15/2009',
 '01-01-2015',
 '06-03-2010',
 '07-08-2007',
 '08-08-2012',
 '04-04-2015',
 '12/15/2012']

In [301]:
stores["Open Date"].nunique()

25

In [302]:
stores["Open Date"] = pd.to_datetime(
    stores["Open Date"],
    format="mixed",
    errors="coerce"
)

In [303]:
stores["Open Date"].dtype

dtype('<M8[ns]')

In [304]:
stores["Open Date"].isna().sum()

np.int64(0)

In [305]:
stores["StoreKey"].isna().sum()

np.int64(0)

In [306]:
stores["StoreKey"].duplicated().sum()

np.int64(0)

In [307]:
stores["StoreKey"].nunique()

67

In [308]:
stores["Country"].unique()

array(['Australia', 'Canada', 'France', 'Germany', 'Italy', 'Netherlands',
       'United Kingdom', 'United States', 'Online'], dtype=object)

In [309]:
stores["Country"].value_counts()

Country
United States     24
Germany            9
United Kingdom     7
France             7
Australia          6
Netherlands        5
Canada             5
Italy              3
Online             1
Name: count, dtype: int64

In [310]:
stores["State"].nunique()

67

In [311]:
stores["State"].value_counts()

State
Australian Capital Territory    1
Northern Territory              1
South Australia                 1
Tasmania                        1
Victoria                        1
                               ..
Utah                            1
Washington DC                   1
West Virginia                   1
Wyoming                         1
Online                          1
Name: count, Length: 67, dtype: int64

In [312]:
stores["Square Meters"].isna().sum()

np.int64(1)

In [313]:
(stores["Square Meters"] <= 0).sum()

np.int64(0)

In [314]:
stores["Square Meters"].describe()

count      66.000000
mean     1402.196970
std       576.404058
min       245.000000
25%      1108.750000
50%      1347.500000
75%      2000.000000
max      2105.000000
Name: Square Meters, dtype: float64

In [315]:
stores[stores["Square Meters"].isna()]

    StoreKey Country   State  Square Meters  Open Date
66         0  Online  Online            NaN 2010-01-01

In [316]:
stores[stores["Square Meters"].isna()].T

                                66
StoreKey                         0
Country                     Online
State                       Online
Square Meters                  NaN
Open Date      2010-01-01 00:00:00

In [317]:
# where blank Square Meter is present that replaced by 0
stores["Square Meters"] = stores["Square Meters"].fillna(0)

In [318]:
stores["Square Meters"].isna().sum()

np.int64(0)

In [319]:
stores["Open Date"].isna().sum()

np.int64(0)

In [320]:
stores["Open Date"].min(), stores["Open Date"].max()

(Timestamp('2005-03-04 00:00:00'), Timestamp('2019-03-05 00:00:00'))

In [321]:
# Check for invalid/Unsual dates
(stores["Open Date"] > pd.Timestamp.today()).sum()

np.int64(0)

In [322]:
stores.dtypes

StoreKey                  int64
Country                  object
State                    object
Square Meters           float64
Open Date        datetime64[ns]
dtype: object

In [323]:
df["StoreKey"].isin(stores["StoreKey"]).mean() * 100

np.float64(100.0)

In [324]:
df[~df["StoreKey"].isin(stores["StoreKey"])]

Empty DataFrame
Columns: [Order Number, Line Item, Order Date, Delivery Date, CustomerKey, StoreKey, ProductKey, Quantity, Currency Code]
Index: []

# Product Table

In [325]:
products = pd.read_csv("Products.csv")

In [326]:
products.shape

(2517, 10)

In [327]:
products.columns

Index(['ProductKey', 'Product Name', 'Brand', 'Color', 'Unit Cost USD',
       'Unit Price USD', 'SubcategoryKey', 'Subcategory', 'CategoryKey',
       'Category'],
      dtype='object')

In [328]:
products.head()

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [329]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ProductKey      2517 non-null   int64
 1   Product Name    2517 non-null   object
 2   Brand           2517 non-null   object
 3   Color           2517 non-null   object
 4   Unit Cost USD   2517 non-null   object
 5   Unit Price USD  2517 non-null   object
 6   SubcategoryKey  2517 non-null   int64
 7   Subcategory     2517 non-null   object
 8   CategoryKey     2517 non-null   int64
 9   Category        2517 non-null   object
dtypes: int64(3), object(7)
memory usage: 196.8+ KB

In [330]:
products.isna().sum()

ProductKey        0
Product Name      0
Brand             0
Color             0
Unit Cost USD     0
Unit Price USD    0
SubcategoryKey    0
Subcategory       0
CategoryKey       0
Category          0
dtype: int64

In [331]:
products["ProductKey"].duplicated().sum()

np.int64(0)

In [332]:
products["Unit Cost USD"].head(10)

0     $6.62
1     $6.62
2     $7.40
3    $11.00
4    $11.00
5    $11.00
6    $11.00
7    $30.58
8    $30.58
9    $30.58
Name: Unit Cost USD, dtype: object

In [333]:
products["Unit Price USD"].head(10)

0    $12.99
1    $12.99
2    $14.52
3    $21.57
4    $21.57
5    $21.57
6    $21.57
7    $59.99
8    $59.99
9    $59.99
Name: Unit Price USD, dtype: object

In [334]:
products["Color"].value_counts().head(20)

Color
Black          602
White          505
Silver         417
Grey           283
Blue           200
Red             99
Pink            84
Brown           77
Green           74
Orange          55
Gold            50
Yellow          36
Silver Grey     14
Azure           14
Purple           6
Transparent      1
Name: count, dtype: int64

In [335]:
products["Unit Cost USD"] = (
    products["Unit Cost USD"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)

products["Unit Price USD"] = (
    products["Unit Price USD"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)

In [336]:
products[["Unit Cost USD", "Unit Price USD"]].dtypes

Unit Cost USD     float64
Unit Price USD    float64
dtype: object

In [337]:
(products["Unit Cost USD"] <= 0).sum(), (products["Unit Price USD"] <= 0).sum()

(np.int64(0), np.int64(0))

In [338]:
(products["Unit Price USD"] < products["Unit Cost USD"]).sum()

np.int64(0)

In [339]:
df["ProductKey"].isin(products["ProductKey"]).mean() * 100

np.float64(100.0)

In [340]:
df[~df["ProductKey"].isin(products["ProductKey"])]

Empty DataFrame
Columns: [Order Number, Line Item, Order Date, Delivery Date, CustomerKey, StoreKey, ProductKey, Quantity, Currency Code]
Index: []

In [341]:
# Renaming the columns of the sales table.
df.columns = [
    "order_number",
    "line_item",
    "order_date",
    "delivery_date",
    "customer_key",
    "store_key",
    "product_key",
    "quantity",
    "currency_code"
]

In [342]:
df.columns

Index(['order_number', 'line_item', 'order_date', 'delivery_date',
       'customer_key', 'store_key', 'product_key', 'quantity',
       'currency_code'],
      dtype='object')

In [343]:
# Renaming the columns of the customers table.
customers.columns = [
    "customer_key",
    "gender",
    "name",
    "city",
    "state_code",
    "state",
    "zip_code",
    "country",
    "continent",
    "birthday"
]

In [344]:
customers.columns

Index(['customer_key', 'gender', 'name', 'city', 'state_code', 'state',
       'zip_code', 'country', 'continent', 'birthday'],
      dtype='object')

In [345]:
# Renaming the columns of the stores table.
stores.columns = [
    "store_key",
    "country",
    "state",
    "square_meters",
    "open_date"
]

In [346]:
stores.columns

Index(['store_key', 'country', 'state', 'square_meters', 'open_date'], dtype='object')

In [347]:
# Renaming the columns of the products table.
products.columns = [
    "product_key",
    "product_name",
    "brand",
    "color",
    "unit_cost_usd",
    "unit_price_usd",
    "subcategory_key",
    "subcategory",
    "category_key",
    "category"
]

In [348]:
products.columns

Index(['product_key', 'product_name', 'brand', 'color', 'unit_cost_usd',
       'unit_price_usd', 'subcategory_key', 'subcategory', 'category_key',
       'category'],
      dtype='object')

# Exchange_rates

In [349]:
exchange_rates = pd.read_csv("Exchange_Rates.csv")

In [350]:
exchange_rates.shape

(11215, 3)

In [351]:
exchange_rates.head()

         Date Currency  Exchange
0  01-01-2015      USD    1.0000
1  01-01-2015      CAD    1.1583
2  01-01-2015      AUD    1.2214
3  01-01-2015      EUR    0.8237
4  01-01-2015      GBP    0.6415

In [352]:
exchange_rates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      11215 non-null  object
 1   Currency  11215 non-null  object
 2   Exchange  11215 non-null  float64
dtypes: float64(1), object(2)
memory usage: 263.0+ KB

In [353]:
exchange_rates["Date"] = pd.to_datetime(exchange_rates["Date"], format="mixed")

In [354]:
exchange_rates.dtypes

Date        datetime64[ns]
Currency            object
Exchange           float64
dtype: object

In [355]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("Sanju@123")
host = "localhost"
port = "5432"
database = "Maven_Market_Analytics"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

print("Connection object created successfully!")

Connection object created successfully!

In [356]:
with engine.connect() as connection:
    print("Database connected successfully!")

Database connected successfully!

In [357]:
df.to_sql(
    "sales",
    con=engine,
    if_exists="replace",
    index=False
)

customers.to_sql(
    "customers",
    con=engine,
    if_exists="replace",
    index=False
)

stores.to_sql(
    "stores",
    con=engine,
    if_exists="replace",
    index=False
)

products.to_sql(
    "products",
    con=engine,
    if_exists="replace",
    index=False
)

exchange_rates.to_sql(
    "exchange_rates",
    con=engine,
    if_exists="replace",
    index=False
)

print("All tables loaded successfully!")

All tables loaded successfully!